// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArT6e0W5mAzLRSYmrMVRi38ALB_9IQVc0',
    appId: '1:225211895869:web:4fc971f540796300211a54',
    messagingSenderId: '225211895869',
    projectId: 'chinmayi-e6222',
    authDomain: 'chinmayi-e6222.firebaseapp.com',
    storageBucket: 'chinmayi-e6222.appspot.com',
    measurementId: 'G-DDJF71PRCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzoK71rQEp7Nh9C7bAR7n63fAi3KuFBA',
    appId: '1:225211895869:android:a52146ff288ec6ab211a54',
    messagingSenderId: '225211895869',
    projectId: 'chinmayi-e6222',
    storageBucket: 'chinmayi-e6222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUF5gaezy0vYjUHokqswiS5vcAmMu6xrg',
    appId: '1:225211895869:ios:b1d62b12b019e0e3211a54',
    messagingSenderId: '225211895869',
    projectId: 'chinmayi-e6222',
    storageBucket: 'chinmayi-e6222.appspot.com',
    iosBundleId: 'com.example.learnUpMiniproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUF5gaezy0vYjUHokqswiS5vcAmMu6xrg',
    appId: '1:225211895869:ios:b1d62b12b019e0e3211a54',
    messagingSenderId: '225211895869',
    projectId: 'chinmayi-e6222',
    storageBucket: 'chinmayi-e6222.appspot.com',
    iosBundleId: 'com.example.learnUpMiniproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArT6e0W5mAzLRSYmrMVRi38ALB_9IQVc0',
    appId: '1:225211895869:web:37f1cc5a41504e9a211a54',
    messagingSenderId: '225211895869',
    projectId: 'chinmayi-e6222',
    authDomain: 'chinmayi-e6222.firebaseapp.com',
    storageBucket: 'chinmayi-e6222.appspot.com',
    measurementId: 'G-CPSQFWFTV5',
  );
}
